stages:
  - build
  - test

build:pc189:
  stage: build
  tags:
    - pc189
  only:
    - master
  artifacts:
    paths:
      - traffic_sim
  script:
    - source ~/pdmkp_env
    - cmake -DCMAKE_BUILD_TYPE=RELEASE -DWITH_CUDA=OFF -DVISUALIZATION=OFF -DUSE_CIN=ON -DDEBUG_MSGS=OFF -DBUILD_TESTS=OFF .
    - make traffic_sim

build:pc205:
  stage: build
  tags:
    - pc205
  only:
    - master
  artifacts:
    paths:
      - traffic_sim
  script:
    - source ~/pdmkp_env
    - cmake -DCMAKE_BUILD_TYPE=RELEASE -DWITH_CUDA=OFF -DVISUALIZATION=OFF -DUSE_CIN=ON -DDEBUG_MSGS=OFF -DBUILD_TESTS=OFF .
    - make traffic_sim


test:pc189:
  stage: test
  tags:
    - pc189
  only:
    - master
  dependencies:
    - build:pc189
  script:
    - source ~/pdmkp_env
    - traffic_check $PWD/traffic_sim

test:pc205:
  stage: test
  tags:
    - pc205
  only:
    - master
  dependencies:
    - build:pc205
  script:
    - source ~/pdmkp_env
    - traffic_check $PWD/traffic_sim
