# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = .

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = .

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start ./CMakeFiles ./CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start ./CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named traffic_scenario

# Build rule for target.
traffic_scenario: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 traffic_scenario
.PHONY : traffic_scenario

# fast build rule for target.
traffic_scenario/fast:
	$(MAKE) -f CMakeFiles/traffic_scenario.dir/build.make CMakeFiles/traffic_scenario.dir/build
.PHONY : traffic_scenario/fast

#=============================================================================
# Target rules for targets named traffic_sim

# Build rule for target.
traffic_sim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 traffic_sim
.PHONY : traffic_sim

# fast build rule for target.
traffic_sim/fast:
	$(MAKE) -f CMakeFiles/traffic_sim.dir/build.make CMakeFiles/traffic_sim.dir/build
.PHONY : traffic_sim/fast

src/Car.o: src/Car.cpp.o

.PHONY : src/Car.o

# target to build an object file
src/Car.cpp.o:
	$(MAKE) -f CMakeFiles/traffic_scenario.dir/build.make CMakeFiles/traffic_scenario.dir/src/Car.cpp.o
.PHONY : src/Car.cpp.o

src/Car.i: src/Car.cpp.i

.PHONY : src/Car.i

# target to preprocess a source file
src/Car.cpp.i:
	$(MAKE) -f CMakeFiles/traffic_scenario.dir/build.make CMakeFiles/traffic_scenario.dir/src/Car.cpp.i
.PHONY : src/Car.cpp.i

src/Car.s: src/Car.cpp.s

.PHONY : src/Car.s

# target to generate assembly for a file
src/Car.cpp.s:
	$(MAKE) -f CMakeFiles/traffic_scenario.dir/build.make CMakeFiles/traffic_scenario.dir/src/Car.cpp.s
.PHONY : src/Car.cpp.s

src/Junction.o: src/Junction.cpp.o

.PHONY : src/Junction.o

# target to build an object file
src/Junction.cpp.o:
	$(MAKE) -f CMakeFiles/traffic_scenario.dir/build.make CMakeFiles/traffic_scenario.dir/src/Junction.cpp.o
.PHONY : src/Junction.cpp.o

src/Junction.i: src/Junction.cpp.i

.PHONY : src/Junction.i

# target to preprocess a source file
src/Junction.cpp.i:
	$(MAKE) -f CMakeFiles/traffic_scenario.dir/build.make CMakeFiles/traffic_scenario.dir/src/Junction.cpp.i
.PHONY : src/Junction.cpp.i

src/Junction.s: src/Junction.cpp.s

.PHONY : src/Junction.s

# target to generate assembly for a file
src/Junction.cpp.s:
	$(MAKE) -f CMakeFiles/traffic_scenario.dir/build.make CMakeFiles/traffic_scenario.dir/src/Junction.cpp.s
.PHONY : src/Junction.cpp.s

src/Lane.o: src/Lane.cpp.o

.PHONY : src/Lane.o

# target to build an object file
src/Lane.cpp.o:
	$(MAKE) -f CMakeFiles/traffic_scenario.dir/build.make CMakeFiles/traffic_scenario.dir/src/Lane.cpp.o
.PHONY : src/Lane.cpp.o

src/Lane.i: src/Lane.cpp.i

.PHONY : src/Lane.i

# target to preprocess a source file
src/Lane.cpp.i:
	$(MAKE) -f CMakeFiles/traffic_scenario.dir/build.make CMakeFiles/traffic_scenario.dir/src/Lane.cpp.i
.PHONY : src/Lane.cpp.i

src/Lane.s: src/Lane.cpp.s

.PHONY : src/Lane.s

# target to generate assembly for a file
src/Lane.cpp.s:
	$(MAKE) -f CMakeFiles/traffic_scenario.dir/build.make CMakeFiles/traffic_scenario.dir/src/Lane.cpp.s
.PHONY : src/Lane.cpp.s

src/RedTrafficLight.o: src/RedTrafficLight.cpp.o

.PHONY : src/RedTrafficLight.o

# target to build an object file
src/RedTrafficLight.cpp.o:
	$(MAKE) -f CMakeFiles/traffic_scenario.dir/build.make CMakeFiles/traffic_scenario.dir/src/RedTrafficLight.cpp.o
.PHONY : src/RedTrafficLight.cpp.o

src/RedTrafficLight.i: src/RedTrafficLight.cpp.i

.PHONY : src/RedTrafficLight.i

# target to preprocess a source file
src/RedTrafficLight.cpp.i:
	$(MAKE) -f CMakeFiles/traffic_scenario.dir/build.make CMakeFiles/traffic_scenario.dir/src/RedTrafficLight.cpp.i
.PHONY : src/RedTrafficLight.cpp.i

src/RedTrafficLight.s: src/RedTrafficLight.cpp.s

.PHONY : src/RedTrafficLight.s

# target to generate assembly for a file
src/RedTrafficLight.cpp.s:
	$(MAKE) -f CMakeFiles/traffic_scenario.dir/build.make CMakeFiles/traffic_scenario.dir/src/RedTrafficLight.cpp.s
.PHONY : src/RedTrafficLight.cpp.s

src/Road.o: src/Road.cpp.o

.PHONY : src/Road.o

# target to build an object file
src/Road.cpp.o:
	$(MAKE) -f CMakeFiles/traffic_scenario.dir/build.make CMakeFiles/traffic_scenario.dir/src/Road.cpp.o
.PHONY : src/Road.cpp.o

src/Road.i: src/Road.cpp.i

.PHONY : src/Road.i

# target to preprocess a source file
src/Road.cpp.i:
	$(MAKE) -f CMakeFiles/traffic_scenario.dir/build.make CMakeFiles/traffic_scenario.dir/src/Road.cpp.i
.PHONY : src/Road.cpp.i

src/Road.s: src/Road.cpp.s

.PHONY : src/Road.s

# target to generate assembly for a file
src/Road.cpp.s:
	$(MAKE) -f CMakeFiles/traffic_scenario.dir/build.make CMakeFiles/traffic_scenario.dir/src/Road.cpp.s
.PHONY : src/Road.cpp.s

src/Scenario.o: src/Scenario.cpp.o

.PHONY : src/Scenario.o

# target to build an object file
src/Scenario.cpp.o:
	$(MAKE) -f CMakeFiles/traffic_scenario.dir/build.make CMakeFiles/traffic_scenario.dir/src/Scenario.cpp.o
.PHONY : src/Scenario.cpp.o

src/Scenario.i: src/Scenario.cpp.i

.PHONY : src/Scenario.i

# target to preprocess a source file
src/Scenario.cpp.i:
	$(MAKE) -f CMakeFiles/traffic_scenario.dir/build.make CMakeFiles/traffic_scenario.dir/src/Scenario.cpp.i
.PHONY : src/Scenario.cpp.i

src/Scenario.s: src/Scenario.cpp.s

.PHONY : src/Scenario.s

# target to generate assembly for a file
src/Scenario.cpp.s:
	$(MAKE) -f CMakeFiles/traffic_scenario.dir/build.make CMakeFiles/traffic_scenario.dir/src/Scenario.cpp.s
.PHONY : src/Scenario.cpp.s

src/TrafficObject.o: src/TrafficObject.cpp.o

.PHONY : src/TrafficObject.o

# target to build an object file
src/TrafficObject.cpp.o:
	$(MAKE) -f CMakeFiles/traffic_scenario.dir/build.make CMakeFiles/traffic_scenario.dir/src/TrafficObject.cpp.o
.PHONY : src/TrafficObject.cpp.o

src/TrafficObject.i: src/TrafficObject.cpp.i

.PHONY : src/TrafficObject.i

# target to preprocess a source file
src/TrafficObject.cpp.i:
	$(MAKE) -f CMakeFiles/traffic_scenario.dir/build.make CMakeFiles/traffic_scenario.dir/src/TrafficObject.cpp.i
.PHONY : src/TrafficObject.cpp.i

src/TrafficObject.s: src/TrafficObject.cpp.s

.PHONY : src/TrafficObject.s

# target to generate assembly for a file
src/TrafficObject.cpp.s:
	$(MAKE) -f CMakeFiles/traffic_scenario.dir/build.make CMakeFiles/traffic_scenario.dir/src/TrafficObject.cpp.s
.PHONY : src/TrafficObject.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/traffic_sim.dir/build.make CMakeFiles/traffic_sim.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/traffic_sim.dir/build.make CMakeFiles/traffic_sim.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/traffic_sim.dir/build.make CMakeFiles/traffic_sim.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... traffic_scenario"
	@echo "... traffic_sim"
	@echo "... src/Car.o"
	@echo "... src/Car.i"
	@echo "... src/Car.s"
	@echo "... src/Junction.o"
	@echo "... src/Junction.i"
	@echo "... src/Junction.s"
	@echo "... src/Lane.o"
	@echo "... src/Lane.i"
	@echo "... src/Lane.s"
	@echo "... src/RedTrafficLight.o"
	@echo "... src/RedTrafficLight.i"
	@echo "... src/RedTrafficLight.s"
	@echo "... src/Road.o"
	@echo "... src/Road.i"
	@echo "... src/Road.s"
	@echo "... src/Scenario.o"
	@echo "... src/Scenario.i"
	@echo "... src/Scenario.s"
	@echo "... src/TrafficObject.o"
	@echo "... src/TrafficObject.i"
	@echo "... src/TrafficObject.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

